### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by maelle** [lockedata/ibmsunburst#7]
Moved from the README

## Typical htmlwidgets workflow

- [x] Identify JS source
- [x] Use htmlwidgets starter package
- [x] Add relevant JS files to inst
- [x] Include a sample dataset
- [x] Adjust templates to incorporate JS lib
- [x] Prep any data transformation or specifications needed
- [ ] Add testing and documentation
- [ ] Prepare for CRAN
